name: Update TLDR Data News

on:
  schedule:
    # Tourne du lundi au vendredi à 10h UTC
    - cron: '0 10 * * 1-5'
  # Permet de lancer l'action manuellement
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch_and_translate:
    runs-on: ubuntu-latest
    
    # On place les variables d'environnement ici pour tout le job
    env:
      GEMINI_API_KEY: ${{ secrets.TLDR_PORTFOLIO }}
      # Cette ligne supprime les messages d'avertissement sur Node.js 20
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Récupération du code (Checkout)
        uses: actions/checkout@v4
        with:
          # On s'assure d'avoir l'historique pour le commit auto
          fetch-depth: 0

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extraction et Traduction (Script Python)
        run: python scripts/fetch_tldr.py

      - name: Sauvegarde et Mise en ligne (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 [Bot] Mise à jour automatisée de la veille TLDR Data"
          file_pattern: "data/tldr.json"
          # Sécurité : n'échoue pas si aucune modification n'est détectée
          skip_dirty_check: false